# Generated by Django 4.2.7 on 2023-11-12 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='data_exibicao',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='data_hora',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='hora_exibicao',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='texto',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_envio', models.TimeField()),
                ('dia_envio', models.DateField()),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mensagens_programadas', models.ManyToManyField(to='core.mensagem')),
            ],
        ),
    ]
