# Generated by Django 4.2.7 on 2023-11-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_mensagem_data_exibicao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracao',
            old_name='admin',
            new_name='adm',
        ),
    ]
