# Generated by Django 4.2.7 on 2023-11-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_admin_configuracao_adm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='adm',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='mensagens_programadas',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='mensagem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
