# Generated by Django 4.2.7 on 2023-11-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_configuracao_adm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('horario_envio', models.TimeField()),
                ('dia_envio', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Configuracao',
        ),
    ]
