# Generated by Django 4.2.7 on 2023-11-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mensagem_mensagem_adicional_mensagem_ultima'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
