# Generated by Django 4.2.7 on 2023-11-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mensagem_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
