# Generated by Django 4.2.7 on 2023-11-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_mensagem_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='audio_url',
        ),
    ]
