# Generated by Django 4.2.7 on 2023-11-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_mensagem_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='audio_url',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
